name: AI Codereview
on:
  pull_request:
    branches: [ "main" ]
    types:
      - labeled
      - opened
      - synchronize
      - reopened
    paths:
      - '**.go'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Mirantis/ai-ci-scripts
          path: ai-ci-scripts
      - name: Get all changed golang files
        id: changed-golang-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.go
      - uses: actions/setup-python@v5
        id: setup_python
        with:
          python-version: '3.12'
      - name: Restore cached virtualenv
        uses: actions/cache/restore@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('ai-ci-scripts/ai-codereview/requirements.txt') }}
          path: .venv     
      - name: Run ai-codereview script
        id: codereview
        if: steps.changed-golang-files.outputs.any_changed == 'true'
        env:
          AI_API_TOKEN: ${{ secrets.AI_API_TOKEN }}
          AI_API_MODEL: ${{ secrets.AI_API_MODEL }}
          AI_API_BASE_URL: ${{ secrets.AI_API_BASE_URL }}
          MAX_TOKENS: '10000'
          TEMPERATURE: '0.6'
          VENV_DIR_LOC: '.venv'
          LANG: 'go'
          PATH_TO_AI_CODEREVIEW_SCRIPT: 'ai-ci-scripts/ai-codereview/ai-codereview.py'
          PATH_TO_JINJA_TEMPLATE_FILE: 'ai-ci-scripts/ai-codereview/prompt_template.j2'
          PATH_TO_REQUIREMENTS_FILE: 'ai-ci-scripts/ai-codereview/requirements.txt'
          ALL_CHANGED_FILES: ${{ steps.changed-golang-files.outputs.all_changed_files }}
        run: |
          #!/bin/bash -e
          python3 -m venv ${VENV_DIR_LOC}
          set +x
          source ${VENV_DIR_LOC}/bin/activate
          python3 -m pip install -r ${PATH_TO_REQUIREMENTS_FILE}
          echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
          set -x
          for file in $(echo $ALL_CHANGED_FILES) ; do
              echo "Review file ${file}"
              export PROMPT_VAR=$(cat "${file}")
              python3 ${PATH_TO_AI_CODEREVIEW_SCRIPT} \
                --base-url "${AI_API_BASE_URL}" \
                --model "${AI_API_MODEL}"\
                --api-key "${AI_API_TOKEN}" \
                --max-tokens "${MAX_TOKENS}" \
                --temperature "${TEMPERATURE}" \
                --context "" \
                --lang "${LANG}" \
                --template-file "${PATH_TO_JINJA_TEMPLATE_FILE}"
          done
          echo "See the code review here ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> ./summary.txt
          echo "review_result=$(cat ./summary.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - name: Saved cached virtualenv
        uses: actions/cache/save@v4
        with:
          key: venv-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('ai-ci-scripts/ai-codereview/requirements.txt') }}
          path: .venv    
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${{ steps.codereview.outputs.review_result }}"
            })
